### ISSUE TITLE
Images Roadmap

### ISSUE THREAD

**Issue by hspitzer** [scverse/squidpy#134]
Following our discussion on Nov 3rd, here a general roadmap / API for the images part. I've also added open TODOs, so hopefully it should be easy for you to see where there is still help needed. The biggest todos that I see would be evaluating different features and adding plotting functions (including the `extract` function that we discussed). If you decide to take any of the open TODOs on, please create a dedicated issue & discuss details there.

# Images Package
## Functionality
- Process highres histology images (preprocessing, segmentation)
- Extract features from images

## Data organisation
Keep obs/spot-centric data in adata, and image-centric data in ImageContainer. Image visualization function operate on ImageContainer. For feature visualization, create a temporary adata with obsm colum in obs (see extract function below)

ImageContainer:
- Xarray-based, backed by dask, contains several images (histology, segmentation, smoothed image) with same coordinate system
- Has crop functions: crop_equally, crop_spot_generator
- [x] Example notebook: tutorial_imagecontainer
- [x] rename crop function in crop_center and crop_corner. Crop_center only works for uneven diameters. Could give radius. Diameter = 2*radius + 1 @hspitzer 
- [x] `__str__` function for ImageContainer #164 

### Img -> Img: `process_img`
- Segmentation / image filters / preprocessing
- Uses crop_equally and uncrop to process image crop-wise
- [x] example notebook @davidsebfischer 

### Img -> Feature matrix: `calculate_image_features`
- Read from ImageContainer, save results in adata.obsm
- [x] Example notebook: tutorial_feature_extraction.ipynb
- [x] explore / evaluate different feature extraction options (notebook) @Gottfrid91 @LouisK92 

### Feature matrix -> feature matrix: `scaling`
- Status: open PR by @LouisK92 
- [x] add example to hs_extract_image_features_table.ipynb

### Plot images from ImageContainer:
- Use Napari?
- Allow overlay with segmentation mask
- [x] implement - maybe @SabrinaRichter would like to have a look at that? - yes, I will
- [ ] example notebook

### Plot features using adata:
- Extractor function that reorganizes adata, to allow calling of sc.pl functions. E.g. `sc.pl.umap(extract(adata, **kwargs), **kwargs)`
- [x] implement #164 
- [x] example notebook #164 (tutorial_image_plotting_extract)
